service: serverless-image-dl-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: 'arn:aws:s3:::apigateway-test-20211111/*'

functions:
  getImage:
    handler: src/functions/handler.getImage
    events:
      - http:
          path: getImage
          method: get
          cors: true
          response:
            headers:
              Content-Type: "'image/png'"
            contentHandling: CONVERT_TO_BINARY
          integration: lambda
